name : CI/CD Flask App to EC2

on :
  push :
    branches : [ "main" ]  # adjust if needed

jobs :
  deploy :
    name : Deploy to Blue & Green EC2
    runs-on : ubuntu-latest

    steps :
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup-python@v4
      with :
        python-version : '3.9'

    - name : Install dependencies
      run : |
        cd flask-app
        pip install -r requirements.txt

    - name : Run app test (basic import check)
      run : |
        cd flask-app
        python -c "import app"

    - name : Build Docker Image
      run : |
        cd flask-app
        docker build -t flask-image .

    # Optional: push to DockerHub
    - name : Login to DockerHub
      uses : docker/login-action@v2
      with :
         username : ${{ secrets.DOCKER_USERNAME }}
         password : ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run : |
         docker tag flask-image your-dockerhub-username/flask-image
         docker push your-dockerhub-username/flask-image

    - name : Deploy to Blue EC2
      uses : appleboy/ssh-action@master
      with :
        host : ${{ secrets.BLUE_SERVER_IP }}
        username : ${{ secrets.EC2_USER }}
        key : ${{ secrets.SSH_KEY }}
        script : |
          docker stop flask-container || true
          docker rm flask-container || true
          cd ~/flask-app
          git pull origin main
          docker build -t flask-image .
          docker run -d -p 80:80 --name flask-container flask-image

    - name : Deploy to Green EC2
      uses : appleboy/ssh-action@master
      with :
        host : ${{ secrets.GREEN_SERVER_IP }}
        username : ${{ secrets.EC2_USER }}
        key : ${{ secrets.SSH_KEY }}
        script : |
          docker stop flask-container || true
          docker rm flask-container || true
          cd ~/flask-app
          git pull origin main
          docker build -t flask-image .
          docker run -d -p 80:80 --name flask-container flask-image