name: CI/CD Flask App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Blue & Green EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd project-ec2-flask/flask-app
        pip install -r requirements.txt

    - name: Run app test (basic import check)
      run: |
        cd project-ec2-flask/flask-app
        python -c "import app"

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./project-ec2-flask/flask-app
        tags: flask-image
    # Optional: Push to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: ./project-ec2-flask/flask-app
        tags: flask-image
        
    - name: Deploy to Blue EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BLUE_SERVER_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker stop flask-container || true
          sudo docker rm flask-container || true
          rm -rf flask-app || true
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OmkarSG07/devops-project-suite.git flask-app
          cd /home/***/flask-app/project-ec2-flask/flask-app
          sudo docker build -t flask-image .
          sudo docker run -d -p 80:80 --name flask-container flask-image

    - name: Deploy to Green EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GREEN_SERVER_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker stop flask-container || true
          sudo docker rm flask-container || true
          rm -rf flask-app || true
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OmkarSG07/devops-project-suite.git flask-app
          cd /home/***/flask-app/project-ec2-flask/flask-app
          sudo docker build -t flask-image .
          sudo docker run -d -p 80:80 --name flask-container flask-image
